---
# 三鷹駅前
# 
stagename: 三鷹駅前
stagenotice: "チュートリアル"
stageid: test1
ver: 1.0.0 # 2024/2/1 0:00:00
stages:
  - name: 三鷹駅前
    note: "チュートリアル"
    BIT: 5000
    CLK: 5000
itemlists:
  - item: GarbageCube
  - item: GarbageCubeBox
  - item: PowerCube
  - item: Sweeper
  - item: Litter
  - item: Extinguishing # 消火器
  - item: FireCube  # 火事
  # - item: Bugbug  # これは定義にないアイテムなのでエラーになる
goals:
  - building: repair_all
boards:
  - code: ReadMeText1
    text: "掲示板のある場所にむかってください。WASDキーで移動できます。"
  - code: ReadMeText2
    text: "SHIFTキーを押しながら移動すると、はやく移動できます。"
  - code: ReadMeText3
    text: "この光っているパワーキューブはふれると取ることができます。ユニット作成に必要なCLKが増えます。SPACEキーを押すとジャンプできます。"
  - code: ReadMeText4
    text: "この散らばっているゴミはプレイヤーは片付けることができません。TABキーを押してお掃除ロボットを作成し配置してください。"
  - code: ReadMeText5
    text: "お掃除ロボットを右クリックで詳細情報を呼び出すことができます。"
events:
  - time: 0
    event: wind
    value: 5, 225  # 風速, 風向き(0~360 北0度, 東90度, 南180度, 西270度)

  - time: 0.5
    event: spawn_unit
    value: FireCube, random_position

  - time: 1.5
    event: spawn_unit
    value: FireCube, random_position

  - time: 2.5
    event: spawn_unit
    value: FireCube, random_position

  - time: 3.5
    event: spawn_unit
    value: FireCube, random_position

  # - time: 0
  #   event: building_break
  #   value: all
  # - time: 0.5
  #   event: spawn_unit
  #   value: GarbageCubeBox, -185, 40, -58


  # - time: 1
  #   event: earthquake
  #   value: 1.8

  # - time: 3
  #   event: notice
  #   value: "地震が発生しました。"

  # # - time: 3.5
  # #   event: building_break
  # #   value: all
  # - time: 3.5
  #   event: building_break
  #   value: 12



