---
stagename: 三鷹井の頭
stagenotice: "三鷹井の頭"
stageid: 三鷹井の頭
ver: 1.0.1 # 2026/03/04
stages:
  - name: 三鷹井の頭
    note: "三鷹井の頭"
    BIT: 0
    CLK: 0
    # BIT: 1000
    # CLK: 1000
    # mode: debug
itemlists:
  # - item: FireCube  # 火事
  # - item: Litter  # フココロえもん ごみを巻き散らかす   アイテムではない敵ユニイットなので呼び出せない
  - item: DustBox  # ごみ箱
  - item: SentryGuard  # 監視員
  - item: Sweeper
  # - item: GarbageCube
  # - item: GarbageCubeBox
  # - item: PowerCube
  # - item: StopPlate # 止水板
  # - item: WaterTurret # 消火

pathmakers:
  - name: path_marker_start_1
    pos: 0, auto, 160   # Y を auto に → コード側で地面検出

  - name: path_marker_1
    pos: 5.7, auto, 143

  - name: path_marker_goal_1
    pos: 0, auto, 135

  - name: path_marker_start_2
    pos: 20, auto, 160

  - name: path_marker_2
    pos: 18.5, auto, 148

  - name: start_iseya_mae
    pos: 45, auto, 148

  - name: path_marker_3
    pos: 30, auto, 128

  - name: path_marker_4
    pos: 22, auto, 120


  # - name: path_marker_02  # すでに定義済のマーカーは位置のみ変更
  #   pos: 9, 0, 15

routenames:  # ルートでまとめて指定しておけばユニットを呼び出すときに便利
  - name: route_wave1
    markers: path_marker_start_1, path_marker_1, path_marker_goal_1
  
  - name: route_wave2
    markers: path_marker_start_2, path_marker_2, path_marker_goal_1

  - name: route_wave3
    markers: start_iseya_mae, path_marker_3, path_marker_4, path_marker_goal_1


goals:
  # - building: repair_all
  # - garbage: 10, 20  # ゴミの数がｘを超えずｙ秒経過したらステージクリア
  - notfailtime: 300  # ゲームオーバーせずにｙ秒経過したらステージクリア

gameovers:
  # - garbage: 60  # ゴミの数がｘを超えたらゲームオーバー
  # - building: repair_all
  - gameover_type: GarbageOverflow
    threshold: 60   # ごみが規定数を超えたらゲームオーバー

events:
  # ========== 環境設定 ==========
  - time: 0
    event: weather
    value: sunny, 0.00, 0.25, 500

  - time: 0
    event: wind
    value: 2, 0

  # - time: 0
  #   event: watersurface
  #   value: 0  # 任意の高さ

  # ========== テロップ ==========

  - time: 1
    event: telop
    value: "三鷹井の頭"

  - time: 1
    event: subtelop
    value: "ごみを60以下に保ち、5分間耐え抜こう！"


  # ========== Wave 1 ==========
  - time: 1
    event: spawn_unit # 補給
    value: PowerCube, -2, auto, 165, 200

  - time: 1
    event: bloom_path # 経路表示
    value: route_wave1

  - time: 5
    event: subtelop
    value: "wave 1"

  - time: 5
    event: spawn_enemy_unit
    value: Litter, route_wave1

  - time: 8
    event: spawn_enemy_unit
    value: Litter, route_wave1
  # 補足: このような呼び方もできる、同じルートを呼び出すときはルート名だけでもOK
  # value: Litter, path_marker_start_1, path_marker_1, path_marker_goal_1

  - time: 10
    event: spawn_unit_debug # デバッグ用のスポーンイベント
    value: DustBox, 5.8, auto, 153

  - time: 17
    event: spawn_enemy_unit
    value: Litter, route_wave1

  - time: 21
    event: spawn_enemy_unit
    value: Litter, route_wave1

  - time: 21
    event: spawn_unit_debug # デバッグ用のスポーンイベント
    value: Sweeper, 6.7, auto, 140

  - time: 25
    event: spawn_enemy_unit
    value: Litter, route_wave1

  - time: 25
    event: off_bloom_path_complete  # ルート上にいる敵が全ていなくなったらOFFになる
  #   event: off_bloom_path # 呼び出された瞬間OFFになる
    value: route_wave1


  # ========== Wave 2 ==========
  - time: 40
    event: spawn_unit # 補給
    value: PowerCube, -7, auto, 140, 200
  
  - time: 40
    event: bloom_sakura  # 桜咲く
    value: TreeSakura

  - time: 40
    event: spawn_unit
    value: PowerCube, -5, auto, 140, 30

  - time: 40
    event: bloom_path
    value: route_wave2

  - time: 45
    event: subtelop
    value: "wave 2 - 桜開花 -"

  - time: 51
    event: spawn_unit_debug # デバッグ用のスポーンイベント
    value: DustBox, 6, auto, 137.3

  - time: 51
    event: spawn_unit_debug # デバッグ用のスポーンイベント
    value: DustBox, 15, auto, 154

  - time: 55
    event: spawn_enemy_unit
    value: Litter, route_wave2

  - time: 58
    event: spawn_enemy_unit
    value: Litter, route_wave2

  - time: 43
    event: spawn_enemy_unit
    value: Litter, route_wave2

  - time: 45
    event: spawn_unit_debug # デバッグ用のスポーンイベント
    value: Sweeper, 22, auto, 142

  - time: 46
    event: spawn_enemy_unit
    value: Litter, route_wave2

  - time: 49
    event: spawn_enemy_unit
    value: Litter, route_wave2

  - time: 52
    event: spawn_enemy_unit
    value: Litter, route_wave2

  - time: 52
    event: off_bloom_path_complete
    value: route_wave2

  # ========== Wave 3 ==========
  - time: 70
    event: bloom_sakura  # 桜咲く
    value: TreeSakura_01

  - time: 70
    event: spawn_unit
    value: PowerCube, -5, auto, 140, 250

  - time: 70
    event: bloom_path
    value: route_wave3

  - time: 75
    event: subtelop
    value: "wave 3 - 桜 八部咲き -"

  - time: 85
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 90
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 95
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 100
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 105
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 110
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 115
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 135
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 140
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 145
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 92
    event: spawn_unit_debug # デバッグ用のスポーンイベント
    value: Sweeper, 45, auto, 140

  - time: 92
    event: off_bloom_path_complete
    value: route_wave3


  # ========== Wave 4 ==========
  # 総攻撃

  - time: 150
    event: spawn_unit
    value: PowerCube, -15, auto, 140, 150

  - time: 150
    event: spawn_unit
    value: PowerCube, -20, auto, 120, 150

  - time: 150
    event: spawn_unit
    value: PowerCube, -30, auto, 110, 150

  - time: 150
    event: spawn_unit
    value: PowerCube, -50, auto, 100, 150

  - time: 150
    event: spawn_unit
    value: PowerCube, 20, auto, 100, 150

  - time: 180
    event: bloom_path
    value: route_wave1

  - time: 190
    event: bloom_path
    value: route_wave2

  - time: 200
    event: bloom_path
    value: route_wave3

  - time: 210
    event: spawn_enemy_unit
    value: Litter, route_wave1

  - time: 213
    event: spawn_enemy_unit
    value: Litter, route_wave2    

  - time: 216
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 219
    event: spawn_enemy_unit
    value: Litter, route_wave1

  - time: 222
    event: spawn_enemy_unit
    value: Litter, route_wave2

  - time: 225
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 228
    event: spawn_enemy_unit
    value: Litter, route_wave1

  - time: 231
    event: spawn_enemy_unit
    value: Litter, route_wave2    

  - time: 234
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 237
    event: spawn_enemy_unit
    value: Litter, route_wave1

  - time: 240
    event: spawn_enemy_unit
    value: Litter, route_wave2

  - time: 243
    event: spawn_enemy_unit
    value: Litter, route_wave3

  - time: 250
    event: bloom_sakura  # 桜咲く
    value: TreeSakura_02

  - time: 252
    event: subtelop
    value: "wave 4 - 桜 満開 -"

  # - time: 260
  #   event: spawn_unit_debug # デバッグ用のスポーンイベント
  #   value: DustBox, 6, auto, 137.3


  - time: 280
    event: off_bloom_path_complete
    value: route_wave1

  - time: 280
    event: off_bloom_path_complete
    value: route_wave2

  - time: 280
    event: off_bloom_path_complete
    value: route_wave3

  # ========== おまけ ==========

  - time: 350
    event: spawn_unit
    value: FireCube, -21.3, auto, 170

  - time: 350
    event: spawn_unit
    value: FireCube, random_position

  - time: 350
    event: spawn_unit
    value: FireCube, random_position

  - time: 350
    event: spawn_unit
    value: FireCube, random_position

  - time: 350
    event: spawn_unit
    value: FireCube, random_position
